[package]
name = "onednnl-sys"
version = "0.1.0"
edition = "2021"

[lib]
doctest = false

[features]
opencl-gpu-runtime = []
sycl-gpu-runtime = []  

[dependencies]

[build-dependencies]
bindgen = "0.71"
pkg-config = "0.3"
